#!/usr/bin/env sh

if [ -x node_modules/.bin/softvisio-cli ]; then
    node_modules/.bin/softvisio-cli git commit-msg $1 || exit 1
elif [ -x "$(command -v softvisio-cli)" ]; then
    softvisio-cli git commit-msg $1 || exit 1
fi
