#!/usr/bin/env bash

set -Eeuo pipefail

if [[ -x node_modules/.bin/softvisio-cli ]]; then
    node_modules/.bin/softvisio-cli git commit-msg $1
elif [[ -x "$(command -v softvisio-cli)" ]]; then
    softvisio-cli git commit-msg $1
fi
