type: object
properties:
  private: { type: boolean }

  subPackages:
    anyOf:
      - type: "null"
      - type: array
        items: { type: string }
        minItems: 1
        uniqueItems: true

  docker:
    type: object
    properties:
      build:
        type: object
        properties:
          defaultTag: { type: ["null", string] }
          autoTags:
            anyOf:
              - type: "null"
              - type: array
                items: { type: string }
                minItems: 1
                uniqueItems: true

        additionalProperties: false
        required: []

    additionalProperties: false
    required: [build]

  commits:
    type: object
    properties:
      strict: { type: boolean }
      types:
        anyOf:
          - type: "null"
          - { type: array, items: { type: string }, minItems: 1, uniqueItems: true }
      scopeRequired: { type: boolean }
      scopes:
        anyOf:
          - type: "null"
          - { type: array, items: { type: string }, minItems: 1, uniqueItems: true }

    additionalProperties: false
    required: []

additionslProperties: false
required: []
