# DOCS: https://prettier.io/docs/options

# endOfLine: lf # inherited from .editorconfig "end_of_line"
# printWidth: .inf # inherited from .editorconfig "max_line_length"
# tabWidth: 4 # inherited from .editorconfig "indent_size"
# useTabs: false # inherited from .editorconfig "indent_style"

arrowParens: avoid
bracketSameLine: false
bracketSpacing: true
embeddedLanguageFormatting: auto
htmlWhitespaceSensitivity: css
insertPragma: false
jsxSingleQuote: false
objectWrap: preserve
proseWrap: preserve
quoteProps: as-needed
rangeEnd: .inf
rangeStart: 0
requirePragma: false
semi: true
singleAttributePerLine: false
singleQuote: false
trailingComma: es5
vueIndentScriptAndStyle: false
