private: false

subPackages: ~

meta:
    dependabot:
        npm:
            interval: weekly
        docker:
            interval: daily
        github-actions:
            interval: daily
    executables:
        - "**/*.sh"
        - bin/**/*.js
        - tests/**/*.js

docker:
    composeFile: compose.yaml
    defaultTag: ~
    autoTags: ~

commits:
    strict: true

    types:
        - chore
        - feat
        - fix

    scopeRequired: false

    scopes: ~

docs: ~
