releasable: false

subPackages: ~

meta:
  dependabot:
    npm:
      interval: weekly
    docker:
      interval: daily
    github-actions:
      interval: daily

  executables:
    - "**/*.sh"
    - bin/**/*.js
    - tests/**/*.js

  repository:
    archived: ~
    private: ~
    visibility: ~
    hasIssues: true
    hasDiscussions: false
    hasWiki: false
    hasProjects: false
    defaultBranch: ~
    allowForking: ~
    webCommitSignoffRequired: true
    secretScanning: enabled
    secretScanningPushProtection: enabled
    vulnerabilityAlerts: true
    dependabotsecurityupdates: true
    privateVulnerabilityReporting: true

docker:
  composeFile: compose.yaml
  defaultTag: ~
  autoTags: ~

commits:
  strict: true

  types:
    - chore
    - feat
    - fix

  scopeRequired: false

  scopes: ~

docs: ~
