private: false

subPackages: ~

docker:
  composeFile: compose.yaml
  defaultTag: ~
  autoTags: ~

commits:
  strict: true

  types:
    - chore
    - feat
    - fix

  scopeRequired: false

  scopes: ~

docs: ~
