subPackages: ~

meta:
  homepage: ~
  license: ~
  author: ~

  dependabot:
    npm:
      interval: weekly
      day: Monday
      time: 00:00
      timezone: UTC
      open-pull-requests-limit: 5
    docker:
      interval: daily
      day: Monday
      time: 00:00
      timezone: UTC
      open-pull-requests-limit: 5
    github-actions:
      interval: daily
      day: Monday
      time: 00:00
      timezone: UTC
      open-pull-requests-limit: 5

  executables:
    - "**/*.sh"
    - "bin/**/*.js"
    - "tests/**/*.js"

  repository:
    private: ~
    visibility: ~
    hasIssues: true
    hasDiscussions: false
    hasWiki: false
    hasProjects: false
    defaultBranch: ~
    allowForking: ~
    webCommitSignoffRequired: true
    secretScanning: enabled
    secretScanningPushProtection: enabled
    vulnerabilityAlerts: true
    dependabotsecurityupdates: true
    privateVulnerabilityReporting: true

release:
  enabled: false
  branches: [main]

docker:
  composeFile: compose.yaml
  defaultTag: ~
  autoTags: ~

commits:
  requireType: true
  strictType: true

  types:
    feat:
      description: a commit that introduces a new feature to the codebase (MINOR in Semantic Versioning)
      primaryChange: true
      notableChange: true
      requireScope: true
      strictScope: true
    fix:
      description: a commit that patches a bug in your codebase (PATCH in Semantic Versioning)
      primaryChange: true
      notableChange: true
      requireScope: true
      strictScope: true
    refactor:
      description: a code change that neither fixes a bug nor adds a feature
      primaryChange: true
      notableChange: false
      requireScope: true
      strictScope: true

    build:
      description: package build related changes
      requireScope: true
      strictScope: true
    chore:
      description: a commit that does not affect main codebase
      requireScope: true
      strictScope: true
    deps:
      description: package dependencies updates
      requireScope: true
      strictScope: true
    docs:
      description: documentation changes
      requireScope: true
      strictScope: true
    metadata:
      description: package metadata changes
      requireScope: true
      strictScope: true
    release:
      description: package release
      requireScope: true
      strictScope: true
    style:
      description: code stylistic changes
      requireScope: true
      strictScope: true

  scopes: ~

docs: ~
