subPackages: ~

meta:
  homepage: ~
  license: ~
  author: ~

  dependabot:
    npm:
      interval: weekly
      day: Monday
      time: 00:00
      timezone: UTC
      open-pull-requests-limit: 5
    docker:
      interval: daily
      day: Monday
      time: 00:00
      timezone: UTC
      open-pull-requests-limit: 5
    github-actions:
      interval: daily
      day: Monday
      time: 00:00
      timezone: UTC
      open-pull-requests-limit: 5

  executables:
    - "**/*.sh"
    - "bin/**/*.js"
    - "tests/**/*.js"

  repository:
    private: ~
    visibility: ~
    hasIssues: true
    hasDiscussions: false
    hasWiki: false
    hasProjects: false
    defaultBranch: ~
    allowForking: ~
    webCommitSignoffRequired: true
    secretScanning: enabled
    secretScanningPushProtection: enabled
    vulnerabilityAlerts: true
    dependabotsecurityupdates: true
    privateVulnerabilityReporting: true

release:
  enabled: false
  branches: [main]

docker:
  composeFile: compose.yaml
  defaultTag: ~
  autoTags: ~

commits:
  requireType: true
  strictType: true

  types:
    feat:
      primaryChange: true
      notableChange: true
      requireScope: true
      strictScope: true
    fix:
      primaryChange: true
      notableChange: true
      requireScope: true
      strictScope: true
    refactor:
      primaryChange: true
      notableChange: false
      requireScope: true
      strictScope: true
    chore:
      primaryChange: false
      notableChange: false
      requireScope: true
      strictScope: true

  primaryScopes: ~

  secondaryScopes: [deps, docs, lint, metadata, release]

docs: ~
