private: false

subPackages: ~

meta:
  dependabot:
    npm:
      interval: weekly
    docker:
      interval: daily
    github-actions:
      interval: daily
  executables:
    - /**/*.sh
    - /_tests/**/*.js
    - /bin/**/*.js

docker:
  composeFile: compose.yaml
  defaultTag: ~
  autoTags: ~

commits:
  strict: true

  types:
    - chore
    - feat
    - fix

  scopeRequired: false

  scopes: ~

docs: ~
