private: false

subPackages: ~

metadata:
  executables:
    - /_tests/**/*.sh
    - /_tests/**/*.js
    - /bin/**/*.sh
    - /bin/**/*.js

docker:
  composeFile: compose.yaml
  defaultTag: ~
  autoTags: ~

commits:
  strict: true

  types:
    - chore
    - feat
    - fix

  scopeRequired: false

  scopes: ~

docs: ~
