#!/bin/sh

set -e

if [ -f node_modules/.bin/softvisio-cli ] && [ -x "$(command -v npx)" ]; then
    npx softvisio-cli git commit-msg $1
elif [ -x "$(command -v softvisio-cli)" ]; then
    softvisio-cli git commit-msg $1
fi
