type: object
properties:
    label: { type: string }
    maintainer: { type: string, format: email }
    gpgKeyName: { type: string, format: email }
    component: { type: string, format: kebab-case }
    codenames:
        type: array
        items: { type: string }
        minItems: 1
        uniqueItems: true

additionalProperties: false
required: [label, maintainer, gpgKeyName, component, codenames]
