logo: false

types: {}

externalTypes:
  - https://softvisio-node.github.io/core/
  - https://softvisio-node.github.io/result/

aliases:
  /api: https://raw.githubusercontent.com/softvisio-node/core/main/docs/api.md

api:
  location: lib/api
  url: wss://domain.com/api

rpc:
  location: lib/rpc
  url: ws://domain/api
